import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

/**
 * Design-tokens 8.1 and 8.4: a font must be self-hosted, and a missing font
 * file must fail the build rather than show unstyled text on a tester's
 * phone. `fonts.css` is generated by `scripts/fetch-fonts.ts`; this test
 * reads the real file and the real `src/theme/fonts/` directory, so a font
 * file deleted or never committed fails here rather than silently falling
 * back to the system serif.
 */

const THEME_DIR = dirname(fileURLToPath(import.meta.url))
const CSS_PATH = join(THEME_DIR, 'fonts.css')

function referencedFiles(css: string): string[] {
  return [...css.matchAll(/url\(['"]\.\/fonts\/([^'")]+)['"]\)/g)].map((match) => match[1] ?? '')
}

describe('src/theme/fonts.css', () => {
  const css = readFileSync(CSS_PATH, 'utf8')

  it('declares an @font-face rule naming every file it references', () => {
    const files = referencedFiles(css)
    expect(files.length).toBeGreaterThan(0)
    for (const file of files) {
      expect(existsSync(join(THEME_DIR, 'fonts', file)), `${file} is referenced but missing`).toBe(
        true,
      )
    }
  })

  it('ships exactly the two families V0 needs: Italiana and Cormorant (scope 12.3)', () => {
    const families = [...css.matchAll(/font-family:\s*'([^']+)'/g)].map((match) => match[1])
    expect(new Set(families)).toEqual(new Set(['Italiana', 'Cormorant']))
  })

  it('sets font-display: swap on every rule, so text is never invisible while a font loads', () => {
    const rules = [...css.matchAll(/@font-face\s*\{[^}]*\}/g)].map((match) => match[0])
    expect(rules.length).toBeGreaterThan(0)
    for (const rule of rules) expect(rule).toContain('font-display: swap')
  })
})
