import { existsSync, readFileSync, statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { TYPE_ROLES } from './typeScale'
import { shippedTypefaces, TYPE_SLOTS, TYPEFACES } from './typefaces'

/**
 * Design-tokens 8.1 and 8.4: a font must be self-hosted, and a missing font
 * file must fail the build rather than show unstyled text on a tester's phone.
 *
 * `fonts.css` is generated by `scripts/fetch-fonts.ts`; this test reads the real
 * file and the real `src/theme/fonts/` directory, so a font file deleted or
 * never committed fails here rather than silently falling back to the system
 * serif.
 *
 * ## The test that matters is the last one
 *
 * Until session 13 this file asserted that exactly two families shipped, which
 * is a fact about V0 and stops being useful the moment a face is added. What it
 * asserts now is a **rule**: every face the seven typeface options can ask a
 * browser for is declared here and its file is on disk. That is the sentence
 * CLAUDE.md section 9 makes about the registry - "adding a theme is appending an
 * object" - held to account, because an eighth option appended without its fonts
 * fails this test rather than rendering in Georgia on somebody's phone.
 */

const THEME_DIR = dirname(fileURLToPath(import.meta.url))
const CSS_PATH = join(THEME_DIR, 'fonts.css')
const css = readFileSync(CSS_PATH, 'utf8')

interface Rule {
  readonly family: string
  readonly file: string
  readonly weight: number
  readonly style: string
}

/** Every `@font-face` block in the generated stylesheet, read as a record. */
function declaredRules(): Rule[] {
  return [...css.matchAll(/@font-face\s*\{([^}]*)\}/g)].map((match) => {
    const block = match[1] ?? ''
    const read = (property: string) =>
      new RegExp(`${property}:\\s*([^;]+);`).exec(block)?.[1]?.trim() ?? ''
    return {
      family: read('font-family').replace(/'/g, ''),
      file: /url\('\.\/fonts\/([^']+)'\)/.exec(block)?.[1] ?? '',
      weight: Number(read('font-weight')),
      style: read('font-style'),
    }
  })
}

const key = (family: string, weight: number, style: string) =>
  `${family}|${String(weight)}|${style}`

describe('src/theme/fonts.css', () => {
  it('declares an @font-face rule naming every file it references', () => {
    const rules = declaredRules()
    expect(rules.length).toBeGreaterThan(0)
    for (const rule of rules) {
      expect(existsSync(join(THEME_DIR, 'fonts', rule.file)), `${rule.file} is missing`).toBe(true)
      expect(
        statSync(join(THEME_DIR, 'fonts', rule.file)).size,
        `${rule.file} is empty`,
      ).toBeGreaterThan(0)
    }
  })

  it('sets font-display: swap on every rule, so text is never invisible while a font loads', () => {
    const blocks = [...css.matchAll(/@font-face\s*\{[^}]*\}/g)].map((match) => match[0])
    expect(blocks.length).toBeGreaterThan(0)
    for (const block of blocks) expect(block).toContain('font-display: swap')
  })

  it('names only the ten families design-tokens 8.1 lists', () => {
    const families = new Set(declaredRules().map((rule) => rule.family))
    expect([...families].sort()).toEqual([
      'Bodoni Moda',
      'Cinzel Decorative',
      'Cormorant',
      'Cormorant Unicase',
      'EB Garamond',
      'Goudy Bookletter 1911',
      'IM Fell English',
      'IM Fell English SC',
      'Italiana',
      'Tangerine',
    ])
  })

  it('loads no font from a network, which is the whole point of self-hosting', () => {
    // Scope 12.2 and CLAUDE.md rule 11. A CDN font load fails offline and
    // produces unstyled text, on the one morning the app is most needed.
    expect(css).not.toMatch(/https?:/)
    expect(css).not.toContain('//fonts.g')
  })

  it('has a committed file for every face the seven options can ask a browser for', () => {
    // The three slots of every shipped option, plus the body family in italic,
    // which design-tokens 2.2 gives the byline role. This is the same
    // derivation `scripts/fetch-fonts.ts` makes, asserted here against what was
    // actually committed rather than against what the script intended.
    const declared = new Set(
      declaredRules().map((rule) => key(rule.family, rule.weight, rule.style)),
    )

    const missing: string[] = []
    for (const typeface of shippedTypefaces()) {
      for (const name of TYPE_SLOTS) {
        const slot = typeface[name]
        if (!declared.has(key(slot.family, slot.weight, slot.style))) {
          missing.push(
            `${typeface.id} ${name}: ${slot.family} ${String(slot.weight)} ${slot.style}`,
          )
        }
      }
    }

    expect(missing, 'a shipped typeface option has a slot with no committed font file').toEqual([])
  })

  it('has a real italic for the byline of every option but the one with no such cut', () => {
    // Design-tokens 2.2's byline role sits under a title on fourteen screens.
    // Goudy Bookletter 1911 was cut as a single roman and has no italic
    // anywhere, so that one option's byline is slanted by the browser. Every
    // other one is drawn, and this records which is which.
    const declared = new Set(
      declaredRules().map((rule) => key(rule.family, rule.weight, rule.style)),
    )
    const synthesised = shippedTypefaces()
      .filter(({ body }) => !declared.has(key(body.family, body.weight, 'italic')))
      .map((typeface) => typeface.id)

    expect(synthesised).toEqual(['goudy-1911'])
    expect(TYPE_ROLES.bylineItalic.italic).toBe(true)
  })

  it('carries no face the registry does not ask for', () => {
    // A family fetched and committed for an option that was later removed is
    // weight in the service worker's precache and in nobody's interest.
    const wanted = new Set<string>()
    for (const typeface of TYPEFACES) {
      for (const name of TYPE_SLOTS) {
        const slot = typeface[name]
        wanted.add(key(slot.family, slot.weight, slot.style))
      }
      wanted.add(key(typeface.body.family, typeface.body.weight, 'italic'))
    }

    const stray = declaredRules()
      .map((rule) => key(rule.family, rule.weight, rule.style))
      .filter((declared) => !wanted.has(declared))

    expect(stray).toEqual([])
  })
})
