/**
 * Registering the service worker. Scope 12.2: "the app works fully offline."
 *
 * ## Why this does not breach CLAUDE.md rule 11
 *
 * Rule 11 says the application makes no network call, and it means it: no
 * Supabase, no auth, no sync, no telemetry, nothing that leaves the device
 * carrying anything about the person using it. Registering a worker asks the
 * browser for one file, `/sw.js`, from the origin the app was served from, and
 * that worker then caches the app's own files so the app can run without a
 * network at all. It is the opposite of a call out: it is what stops the app
 * needing one. Decision D10.3 records the exception and its boundary, which is
 * that the worker may fetch the app and nothing else.
 *
 * ## What it does, from the user's side
 *
 * First launch: the app is stored on the device. Every launch after that it
 * works in aeroplane mode. When a new build is deployed, it is fetched quietly
 * in the background and is what starts the *next* time the app is opened from
 * cold. Nothing is announced, nothing asks to reload, and no session is
 * interrupted (principle 7.1). The version line at the foot of Settings is how
 * anyone confirms which build they are holding.
 */

/** The worker is generated by the build, so there is nothing to register in dev. */
const SERVICE_WORKER_URL = '/sw.js'

export function registerServiceWorker(): void {
  // Dev is served from memory by Vite and has no generated worker. Registering
  // one there would also mean a cache sitting in front of the thing being
  // edited, which is a debugging session nobody enjoys.
  if (!import.meta.env.PROD) return
  if (!('serviceWorker' in navigator)) return

  // After load, so precaching four megabytes never competes with the first
  // paint of a screen someone opened to pray.
  window.addEventListener('load', () => {
    navigator.serviceWorker.register(SERVICE_WORKER_URL).then(
      (registration) => {
        // Ask once per cold start whether there is a newer build. The browser
        // would get round to it on its own schedule; this makes "deployed
        // yesterday, running today" true rather than roughly true. It fails
        // harmlessly with no network, which is the ordinary case here.
        void registration.update().catch(() => undefined)
      },
      (error: unknown) => {
        // Not fatal. Without a worker the app still runs, it simply needs a
        // network to start, so this is worth a line in the console and nothing
        // on screen.
        console.error('The offline cache could not be set up', error)
      },
    )
  })
}
