import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import subsetFont from 'subset-font'
import { collectCharset } from './lib/fontCharset.ts'

/**
 * The font fetch and subset script (decision D1.8, design-tokens 8.1).
 *
 * V0 ships one typeface option, Italiana, which is Italiana for display and
 * caps and Cormorant for body (scope 12.3, design-tokens 2.1) — the other
 * eight families arrive with the `[v0.1]` typeface picker. Both are OFL
 * Google Fonts, fetched from the canonical `google/fonts` source repository
 * (the same upstream the Google Fonts service itself packages), subset to
 * the characters the committed corpus actually needs, and committed as
 * files, so the app never loads a font from a CDN (CLAUDE.md rule 11,
 * scope 12.2).
 *
 * Run it after `scripts/fetch-corpus.ts`, since the subset depends on the
 * committed corpus text:
 *
 *     node scripts/fetch-fonts.ts
 */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CORPUS_DIR = join(ROOT, 'src', 'data', 'corpus-data')
const FONTS_DIR = join(ROOT, 'src', 'theme', 'fonts')
const FONTS_CSS = join(ROOT, 'src', 'theme', 'fonts.css')

interface FontJob {
  readonly family: string
  readonly sourceUrl: string
  readonly outputFile: string
  readonly weight: string
  readonly style: 'normal' | 'italic'
}

const JOBS: readonly FontJob[] = [
  {
    family: 'Italiana',
    sourceUrl:
      'https://raw.githubusercontent.com/google/fonts/main/ofl/italiana/Italiana-Regular.ttf',
    outputFile: 'Italiana-Regular.woff2',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Cormorant',
    sourceUrl:
      'https://raw.githubusercontent.com/google/fonts/main/ofl/cormorant/Cormorant%5Bwght%5D.ttf',
    outputFile: 'Cormorant-VariableFont_wght.woff2',
    weight: '400',
    style: 'normal',
  },
]

async function corpusCharset(): Promise<string> {
  const files = [
    'prayers.json',
    'hidden-words.json',
    'gleanings.json',
    'prayers-and-meditations.json',
    'tags.json',
  ]
  const texts: string[] = []
  for (const file of files) {
    const rows = JSON.parse(await readFile(join(CORPUS_DIR, file), 'utf8')) as Record<
      string,
      unknown
    >[]
    for (const row of rows) {
      for (const value of Object.values(row)) {
        if (typeof value === 'string') texts.push(value)
      }
    }
  }
  return collectCharset(texts)
}

async function fetchFontSource(url: string): Promise<Buffer> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`${url} responded ${String(response.status)} ${response.statusText}`)
  }
  return Buffer.from(await response.arrayBuffer())
}

function fontFaceRule(job: FontJob): string {
  return [
    '@font-face {',
    `  font-family: '${job.family}';`,
    `  src: url('./fonts/${job.outputFile}') format('woff2');`,
    `  font-weight: ${job.weight};`,
    `  font-style: ${job.style};`,
    '  font-display: swap;',
    '}',
  ].join('\n')
}

async function main(): Promise<void> {
  await mkdir(FONTS_DIR, { recursive: true })

  const charset = await corpusCharset()
  console.log(
    `Subsetting to ${String(charset.length)} distinct characters found in the committed corpus.`,
  )

  const rules: string[] = []
  for (const job of JOBS) {
    const source = await fetchFontSource(job.sourceUrl)
    const subset = await subsetFont(source, charset, { targetFormat: 'woff2' })
    await writeFile(join(FONTS_DIR, job.outputFile), subset)
    console.log(
      `${job.family}: ${String(source.length)} bytes -> ${String(subset.length)} bytes (${job.outputFile})`,
    )
    rules.push(fontFaceRule(job))
  }

  const css =
    '/**\n' +
    ' * Self-hosted @font-face rules (decision D1.8, design-tokens 8.1).\n' +
    ' *\n' +
    ' * Generated by `scripts/fetch-fonts.ts`. Never hand-edit: change the script\n' +
    ' * and re-run it (CLAUDE.md rule 12 applies here exactly as it does to the\n' +
    ' * corpus JSON). Subset to the characters the committed corpus actually uses\n' +
    ' * (`scripts/lib/fontCharset.ts`), so a diacritic missing from this file\n' +
    ' * means re-running the script, not editing it by hand.\n' +
    ' *\n' +
    ' * Only Italiana and Cormorant ship in V0 (scope 12.3): Italiana supplies the\n' +
    ' * display and caps slots, Cormorant supplies body. The other eight families\n' +
    ' * named in `src/theme/typefaces.ts` arrive with the `[v0.1]` typeface picker.\n' +
    ' */\n\n' +
    `${rules.join('\n\n')}\n`
  await writeFile(FONTS_CSS, css, 'utf8')

  console.log(`Wrote ${FONTS_CSS}`)
}

await main()
